name: Build and Push Docker image

on: 
    push:
        branches: [master]

jobs: 
    push_to_dockerhub:
        name: Push Docker image to docker hub
        runs-on: ubuntu-latest
        steps:
          - name: Check out no repositorio
            uses: actions/checkout@v3

          - name: setup JDK
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '17'
          
          - name: Build com Maven
            run: mvn package

          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and push
            uses: docker/build-push-action@v4
            with:
              push: true
              tags: flaviogm/counter

          
          